// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZm-MNVDEE55T_eh7L_dJILNFKAmWzXE',
    appId: '1:1055175274311:web:b29381a1a81bd9a59fe662',
    messagingSenderId: '1055175274311',
    projectId: 'educonnect-c8977',
    authDomain: 'educonnect-c8977.firebaseapp.com',
    storageBucket: 'educonnect-c8977.appspot.com',
    measurementId: 'G-T452BHJ8XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GFw0WT52NT9kGJB39_EQbsv2Srj8p2Q',
    appId: '1:1055175274311:android:97b79d2eaa354e099fe662',
    messagingSenderId: '1055175274311',
    projectId: 'educonnect-c8977',
    storageBucket: 'educonnect-c8977.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnKvbUNAuB3ii6lerN48GNKHbuXUPWKh0',
    appId: '1:1055175274311:ios:d739602dbd0f2f9b9fe662',
    messagingSenderId: '1055175274311',
    projectId: 'educonnect-c8977',
    storageBucket: 'educonnect-c8977.appspot.com',
    iosBundleId: 'com.example.basreng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnKvbUNAuB3ii6lerN48GNKHbuXUPWKh0',
    appId: '1:1055175274311:ios:456d7be0261b9f3b9fe662',
    messagingSenderId: '1055175274311',
    projectId: 'educonnect-c8977',
    storageBucket: 'educonnect-c8977.appspot.com',
    iosBundleId: 'com.example.basreng.RunnerTests',
  );
}
